export const process = {
  version: 'v14.17.1',
  versions: {
    node: '14.17.1',
    v8: '8.4.371.23-node.67',
    uv: '1.41.0',
    zlib: '1.2.11',
    brotli: '1.0.9',
    ares: '1.17.1',
    modules: '83',
    nghttp2: '1.42.0',
    napi: '8',
    llhttp: '2.1.3',
    openssl: '1.1.1k',
    cldr: '39.0',
    icu: '69.1',
    tz: '2021a',
    unicode: '13.0'
  },
  arch: 'x64',
  platform: 'win32',
  release: {
    name: 'node',
    lts: 'Fermium',
    sourceUrl: 'https://nodejs.org/download/release/v14.17.1/node-v14.17.1.tar.gz',
    headersUrl: 'https://nodejs.org/download/release/v14.17.1/node-v14.17.1-headers.tar.gz',
    libUrl: 'https://nodejs.org/download/release/v14.17.1/win-x64/node.lib'
  },
  _rawDebug: [Function: _rawDebug],
  moduleLoadList: [
    'Internal Binding native_module',
    'Internal Binding errors',
    'NativeModule internal/errors',
    'Internal Binding config',
    'Internal Binding constants',
    'Internal Binding util',
    'Internal Binding types',
    'NativeModule internal/util',
    'NativeModule internal/util/types',
    'NativeModule internal/assert',
    'Internal Binding icu',
    'NativeModule internal/util/inspect',
    'NativeModule internal/validators',
    'NativeModule events',
    'Internal Binding buffer',
    'Internal Binding string_decoder',
    'NativeModule internal/buffer',
    'NativeModule buffer',
    'Internal Binding symbols',
    'Internal Binding messaging',
    'NativeModule internal/worker/js_transferable',
    'NativeModule internal/process/per_thread',
    'Internal Binding process_methods',
    'Internal Binding credentials',
    'Internal Binding async_wrap',
    'Internal Binding task_queue',
    'NativeModule internal/async_hooks',
    'NativeModule internal/process/promises',
    'NativeModule internal/fixed_queue',
    'NativeModule async_hooks',
    'NativeModule internal/process/task_queues',
    'Internal Binding trace_events',
    'NativeModule internal/constants',
    'NativeModule internal/console/constructor',
    'NativeModule internal/console/global',
    'NativeModule internal/util/inspector',
    'Internal Binding inspector',
    'NativeModule internal/querystring',
    'NativeModule path',
    'Internal Binding url',
    'NativeModule internal/url',
    'NativeModule internal/encoding',
    'Internal Binding timers',
    'NativeModule internal/linkedlist',
    'NativeModule internal/priority_queue',
    'NativeModule internal/util/debuglog',
    'NativeModule internal/timers',
    'NativeModule timers',
    'NativeModule internal/process/execution',
    'NativeModule internal/process/warning',
    'NativeModule internal/process/signal',
    'Internal Binding options',
    'NativeModule internal/options',
    'NativeModule internal/bootstrap/pre_execution',
    'NativeModule internal/inspector_async_hook',
    'Internal Binding report',
    'NativeModule internal/process/report',
    'Internal Binding fs',
    'NativeModule internal/fs/utils',
    'Internal Binding fs_dir',
    'NativeModule internal/fs/dir',
    'NativeModule fs',
    'NativeModule internal/util/iterable_weak_map',
    'NativeModule internal/modules/cjs/helpers',
    'NativeModule internal/source_map/source_map_cache',
    'Internal Binding contextify',
    'NativeModule vm',
    'NativeModule internal/idna',
    'NativeModule url',
    'NativeModule internal/modules/package_json_reader',
    'Internal Binding module_wrap',
    'NativeModule internal/modules/esm/module_job',
    'NativeModule internal/modules/esm/module_map',
    'NativeModule internal/modules/esm/resolve',
    'NativeModule internal/modules/esm/get_format',
    'NativeModule internal/fs/rimraf',
    'NativeModule internal/fs/promises',
    'NativeModule internal/modules/esm/get_source',
    'NativeModule internal/modules/esm/transform_source',
    'NativeModule internal/modules/esm/create_dynamic_module',
    'NativeModule internal/modules/esm/translators',
    'NativeModule internal/modules/esm/loader',
    'NativeModule internal/vm/module',
    'NativeModule internal/process/esm_loader',
    'NativeModule internal/modules/cjs/loader',
    'NativeModule internal/modules/run_main',
    'Internal Binding os',
    'NativeModule os',
    'NativeModule internal/streams/destroy',
    'NativeModule internal/streams/pipeline',
    'NativeModule internal/streams/end-of-stream',
    'NativeModule internal/streams/legacy',
    'NativeModule internal/streams/buffer_list',
    'NativeModule internal/streams/state',
    'NativeModule internal/streams/readable',
    'NativeModule internal/streams/writable',
    'NativeModule internal/streams/duplex',
    'NativeModule internal/streams/transform',
    'NativeModule internal/streams/passthrough',
    'NativeModule stream',
    ... 105 more items
  ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events: [Object: null prototype] {
    newListener: [ [Function: startListeningIfSignal], [Function (anonymous)] ],
    removeListener: [ [Function: stopListeningIfSignal], [Function (anonymous)] ],
    warning: [Function: onWarning],
    SIGWINCH: [ [Function (anonymous)], [Function (anonymous)] ],
    SIGTERM: [Function (anonymous)],
    SIGINT: [Function (anonymous)],
    unhandledRejection: [Function (anonymous)],
    uncaughtException: [
      [Function: domainUncaughtExceptionClear],
      [Function (anonymous)]
    ]
  },
  _eventsCount: 8,
  _maxListeners: undefined,
  domain: [Getter/Setter],
  _exiting: false,
  config: {
    target_defaults: {
      cflags: [],
      default_configuration: 'Release',
      defines: [],
      include_dirs: [],
      libraries: []
    },
    variables: {
      asan: 0,
      build_v8_with_gn: false,
      coverage: false,
      dcheck_always_on: 0,
      debug_nghttp2: false,
      debug_node: false,
      enable_lto: false,
      enable_pgo_generate: false,
      enable_pgo_use: false,
      error_on_warn: false,
      force_dynamic_crt: 0,
      host_arch: 'x64',
      icu_data_in: '..\\..\\deps\\icu-tmp\\icudt69l.dat',
      icu_endianness: 'l',
      icu_gyp_path: 'tools/icu/icu-generic.gyp',
      icu_path: 'deps/icu-small',
      icu_small: false,
      icu_ver_major: '69',
      is_debug: 0,
      napi_build_version: '8',
      nasm_version: '2.14',
      node_byteorder: 'little',
      node_debug_lib: false,
      node_enable_d8: false,
      node_install_npm: true,
      node_module_version: 83,
      node_no_browser_globals: false,
      node_prefix: '/usr/local',
      node_release_urlbase: 'https://nodejs.org/download/release/',
      node_shared: false,
      node_shared_brotli: false,
      node_shared_cares: false,
      node_shared_http_parser: false,
      node_shared_libuv: false,
      node_shared_nghttp2: false,
      node_shared_openssl: false,
      node_shared_zlib: false,
      node_tag: '',
      node_target_type: 'executable',
      node_use_bundled_v8: true,
      node_use_dtrace: false,
      node_use_etw: true,
      node_use_node_code_cache: true,
      node_use_node_snapshot: true,
      node_use_openssl: true,
      node_use_v8_platform: true,
      node_with_ltcg: true,
      node_without_node_options: false,
      openssl_fips: '',
      openssl_is_fips: false,
      ossfuzz: false,
      shlib_suffix: 'so.83',
      target_arch: 'x64',
      v8_enable_31bit_smis_on_64bit_arch: 0,
      v8_enable_gdbjit: 0,
      v8_enable_i18n_support: 1,
      v8_enable_inspector: 1,
      v8_enable_lite_mode: 0,
      v8_enable_object_print: 1,
      v8_enable_pointer_compression: 0,
      v8_no_strict_aliasing: 1,
      v8_optimized_debug: 1,
      v8_promise_internal_field_count: 1,
      v8_random_seed: 0,
      v8_trace_maps: 0,
      v8_use_siphash: 1,
      want_separate_host_toolset: 0
    }
  },
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  reallyExit: [Function: reallyExit],
  _kill: [Function: _kill],
  hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
  cpuUsage: [Function: cpuUsage],
  resourceUsage: [Function: resourceUsage],
  memoryUsage: [Function: memoryUsage],
  kill: [Function: kill],
  exit: [Function: exit],
  openStdin: [Function (anonymous)],
  allowedNodeEnvironmentFlags: NodeEnvironmentFlagsSet(96) [Set] {
    '--icu-data-dir',
    '--title',
    '--experimental-import-meta-resolve',
    '--use-largepages',
    '--trace-tls',
    '--trace-event-categories',
    '--conditions',
    '--trace-event-file-pattern',
    '--v8-pool-size',
    '--zero-fill-buffers',
    '--trace-sync-io',
    '--trace-atomics-wait',
    '--disallow-code-generation-from-strings',
    '--force-context-aware',
    '--report-dir',
    '--disable-proto',
    '--experimental-worker',
    '--diagnostic-dir',
    '--debug-arraybuffer-allocations',
    '--pending-deprecation',
    '--use-bundled-ca',
    '--report-filename',
    '--report-compact',
    '--report-on-fatalerror',
    '--perf-prof',
    '--report-signal',
    '--preserve-symlinks-main',
    '--openssl-config',
    '--tls-cipher-list',
    '--use-openssl-ca',
    '--trace-sigint',
    '--no-node-snapshot',
    '--track-heap-objects',
    '--experimental-repl-await',
    '--experimental-json-modules',
    '--abort-on-uncaught-exception',
    '--interpreted-frames-native-stack',
    '--perf-basic-prof-only-functions',
    '--max-old-space-size',
    '--perf-basic-prof',
    '--perf-prof-unwinding-info',
    '--stack-trace-limit',
    '--jitless',
    '--experimental-top-level-await',
    '--require',
    '--huge-max-old-generation-size',
    '--report-uncaught-exception',
    '--report-on-signal',
    '--experimental-policy',
    '--experimental-abortcontroller',
    '--enable-source-maps',
    '--experimental-loader',
    '--experimental-modules',
    '--experimental-wasm-modules',
    '--policy-integrity',
    '--experimental-vm-modules',
    '--experimental-report',
    '--experimental-wasi-unstable-preview1',
    '--trace-uncaught',
    '--insecure-http-parser',
    '--frozen-intrinsics',
    '--tls-keylog',
    '--input-type',
    '--heapsnapshot-signal',
    '--http-parser',
    '--experimental-specifier-resolution',
    '--no-deprecation',
    '--tls-min-v1.0',
    '--no-force-async-hooks-checks',
    '--no-warnings',
    '--preserve-symlinks',
    '--tls-min-v1.1',
    '--trace-exit',
    '--throw-deprecation',
    '--max-http-header-size',
    '--redirect-warnings',
    '--trace-deprecation',
    '--trace-warnings',
    '--unhandled-rejections',
    '--verify-base-objects',
    '--inspect',
    '--napi-modules',
    '--tls-min-v1.2',
    '--tls-min-v1.3',
    '--tls-max-v1.2',
    '--tls-max-v1.3',
    '--inspect-port',
    '--inspect-brk',
    '--inspect-publish-uid',
    '--debug-port',
    '--trace-events-enabled',
    '--report-directory',
    '--es-module-specifier-resolution',
    '--loader',
    '--prof-process',
    '-r'
  },
  assert: [Function: deprecated],
  features: {
    inspector: true,
    debug: false,
    uv: true,
    ipv6: true,
    tls_alpn: true,
    tls_sni: true,
    tls_ocsp: true,
    tls: true,
    cached_builtins: true
  },
  _fatalException: [Function (anonymous)],
  setUncaughtExceptionCaptureCallback: [Function (anonymous)],
  hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
  emitWarning: [Function: emitWarning],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: runNextTicks],
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function (anonymous)],
  _stopProfilerIdleNotifier: [Function (anonymous)],
  stdout: [Getter],
  stdin: [Getter],
  stderr: [Getter],
  abort: [Function: abort],
  umask: [Function: wrappedUmask],
  chdir: [Function (anonymous)],
  cwd: [Function (anonymous)],
  env: {
    ALLUSERSPROFILE: 'C:\\ProgramData',
    ANDROID_HOME: 'C:\\Users\\Zz\\AppData\\Local\\Android\\Sdk',
    APPDATA: 'C:\\Users\\Zz\\AppData\\Roaming',
    'asl.log': 'Destination=file',
    CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_12972_DEAZACSYHRFYICVX',
    CLASSPATH: '.;C:\\Program Files\\Java\\jdk1.8.0_301\\bin;C:\\Program Files\\Java\\jdk1.8.0_301\\lib\\dt.jar;C:\\Program Files\\Java\\jdk1.8.0_301\\lib\\tools.jar',
    COLORTERM: 'truecolor',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-GQBECKU',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    GIT_ASKPASS: 'd:\\application\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
    HOME: 'C:\\Users\\Zz',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Zz',
    INIT_CWD: 'D:\\workspace\\new-share',
    INTEL_DEV_REDIST: 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\',
    JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.8.0_301',
    LANG: 'en_US.UTF-8',
    LOCALAPPDATA: 'C:\\Users\\Zz\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-GQBECKU',
    MIC_LD_LIBRARY_PATH: 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic',
    NODE: 'C:\\Program Files\\nodejs\\node.exe',
    NODE_ENV: 'development',
    NODE_EXE: 'C:\\Program Files\\nodejs\\\\node.exe',
    NPM_CLI_JS: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    npm_config_access: '',
    npm_config_allow_same_version: '',
    npm_config_also: '',
    npm_config_always_auth: '',
    npm_config_argv: '{"remain":[],"cooked":["run","dev"],"original":["run","dev"]}',
    npm_config_audit: 'true',
    npm_config_audit_level: 'low',
    npm_config_auth_type: 'legacy',
    npm_config_before: '',
    npm_config_bin_links: 'true',
    npm_config_browser: '',
    npm_config_ca: '',
    npm_config_cache: 'C:\\Users\\Zz\\AppData\\Roaming\\npm-cache',
    npm_config_cache_lock_retries: '10',
    npm_config_cache_lock_stale: '60000',
    npm_config_cache_lock_wait: '10000',
    npm_config_cache_max: 'Infinity',
    npm_config_cache_min: '10',
    npm_config_cafile: '',
    npm_config_cert: '',
    npm_config_cidr: '',
    npm_config_color: 'true',
    npm_config_commit_hooks: 'true',
    npm_config_depth: 'Infinity',
    npm_config_description: 'true',
    npm_config_dev: '',
    npm_config_dry_run: '',
    npm_config_editor: 'notepad.exe',
    npm_config_engine_strict: '',
    npm_config_fetch_retries: '2',
    npm_config_fetch_retry_factor: '10',
    npm_config_fetch_retry_maxtimeout: '60000',
    npm_config_fetch_retry_mintimeout: '10000',
    npm_config_force: '',
    npm_config_format_package_lock: 'true',
    npm_config_fund: 'true',
    npm_config_git: 'git',
    npm_config_git_tag_version: 'true',
    npm_config_global: '',
    npm_config_globalconfig: 'C:\\Program Files\\nodejs\\etc\\npmrc',
    npm_config_globalignorefile: 'C:\\Program Files\\nodejs\\etc\\npmignore',
    npm_config_global_style: '',
    npm_config_group: '',
    npm_config_ham_it_up: '',
    npm_config_heading: 'npm',
    npm_config_https_proxy: '',
    npm_config_if_present: '',
    npm_config_ignore_prepublish: '',
    npm_config_ignore_scripts: '',
    npm_config_init_author_email: '',
    npm_config_init_author_name: '',
    npm_config_init_author_url: '',
    npm_config_init_license: 'ISC',
    npm_config_init_module: 'C:\\Users\\Zz\\.npm-init.js',
    npm_config_init_version: '1.0.0',
    npm_config_json: '',
    npm_config_key: '',
    npm_config_legacy_bundling: '',
    npm_config_link: '',
    npm_config_local_address: '',
    npm_config_loglevel: 'notice',
    npm_config_logs_max: '10',
    npm_config_long: '',
    npm_config_maxsockets: '50',
    npm_config_message: '%s',
    npm_config_metrics_registry: 'http://registry.npm.taobao.org/',
    npm_config_node_gyp: 'D:\\application\\nvm\\v14.17.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
    npm_config_node_options: '',
    npm_config_node_version: '14.17.1',
    npm_config_noproxy: '',
    npm_config_offline: '',
    npm_config_onload_script: '',
    npm_config_only: '',
    npm_config_optional: 'true',
    npm_config_otp: '',
    npm_config_package_lock: 'true',
    npm_config_package_lock_only: '',
    npm_config_parseable: '',
    npm_config_prefer_offline: '',
    npm_config_prefer_online: '',
    npm_config_prefix: 'C:\\Program Files\\nodejs',
    npm_config_preid: '',
    npm_config_production: '',
    npm_config_progress: 'true',
    npm_config_proxy: '',
    npm_config_read_only: '',
    npm_config_rebuild_bundle: 'true',
    npm_config_registry: 'http://registry.npm.taobao.org/',
    npm_config_rollback: 'true',
    npm_config_save: 'true',
    npm_config_save_bundle: '',
    npm_config_save_dev: '',
    npm_config_save_exact: '',
    npm_config_save_optional: '',
    npm_config_save_prefix: '^',
    npm_config_save_prod: '',
    npm_config_scope: '',
    npm_config_scripts_prepend_node_path: 'warn-only',
    npm_config_script_shell: '',
    npm_config_searchexclude: '',
    npm_config_searchlimit: '20',
    npm_config_searchopts: '',
    npm_config_searchstaleness: '900',
    npm_config_send_metrics: '',
    npm_config_shell: 'C:\\Windows\\system32\\cmd.exe',
    npm_config_shrinkwrap: 'true',
    npm_config_sign_git_commit: '',
    npm_config_sign_git_tag: '',
    npm_config_sso_poll_frequency: '500',
    npm_config_sso_type: 'oauth',
    npm_config_strict_ssl: 'true',
    npm_config_tag: 'latest',
    npm_config_tag_version_prefix: 'v',
    npm_config_timing: '',
    npm_config_tmp: 'C:\\Users\\Zz\\AppData\\Local\\Temp',
    npm_config_umask: '0000',
    npm_config_unicode: '',
    npm_config_unsafe_perm: 'true',
    npm_config_update_notifier: 'true',
    npm_config_usage: '',
    npm_config_user: '',
    npm_config_userconfig: 'C:\\Users\\Zz\\.npmrc',
    npm_config_user_agent: 'npm/6.14.13 node/v14.17.1 win32 x64',
    npm_config_version: '',
    npm_config_versions: '',
    npm_config_viewer: 'browser',
    npm_execpath: 'D:\\application\\nvm\\v14.17.1\\node_modules\\npm\\bin\\npm-cli.js',
    npm_lifecycle_event: 'dev',
    npm_lifecycle_script: 'next dev',
    npm_node_execpath: 'C:\\Program Files\\nodejs\\node.exe',
    npm_package_dependencies_antd_mobile: '^5.4.0',
    npm_package_dependencies_axios: '^0.26.1',
    npm_package_dependencies_cross_env: '^7.0.3',
    npm_package_dependencies_js_cookie: '^3.0.1',
    npm_package_dependencies_koa: '^2.13.4',
    npm_package_dependencies_lodash_debounce: '^4.0.8',
    npm_package_dependencies_lodash_omit: '^4.5.0',
    npm_package_dependencies_next: '12.1.0',
    npm_package_dependencies_postcss_px_to_viewport: '^1.1.1',
    npm_package_dependencies_qs: '^6.10.3',
    npm_package_dependencies_react: '17.0.2',
    npm_package_dependencies_react_dom: '17.0.2',
    npm_package_dependencies__koa_router: '^10.1.1',
    npm_package_description: 'This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).',
    npm_package_devDependencies_eslint: '8.10.0',
    npm_package_devDependencies_eslint_config_next: '12.1.0',
    npm_package_devDependencies_next_images: '^1.8.4',
    npm_package_devDependencies_next_transpile_modules: '^9.0.0',
    npm_package_devDependencies_postcss_flexbugs_fixes: '^5.0.2',
    npm_package_devDependencies_postcss_preset_env: '^7.4.2',
    npm_package_devDependencies_sass: '^1.49.9',
    npm_package_devDependencies_typescript: '4.6.2',
    npm_package_devDependencies__types_koa: '^2.13.4',
    npm_package_devDependencies__types_lodash_omit: '^4.5.6',
    npm_package_devDependencies__types_node: '17.0.21',
    npm_package_devDependencies__types_qs: '^6.9.7',
    npm_package_devDependencies__types_react: '17.0.39',
    npm_package_gitHead: 'e4c7e83146df73a6e7aeb299da6c96e6dc49f11b',
    npm_package_name: 'new-share',
    npm_package_private: 'true',
    npm_package_readmeFilename: 'README.md',
    npm_package_scripts_build: 'next build',
    npm_package_scripts_dev: 'next dev',
    npm_package_scripts_lint: 'next lint',
    npm_package_scripts_start: 'cross-env NODE_ENV=development node server/index.js',
    npm_package_version: '0.1.0',
    NPM_PREFIX_NPM_CLI_JS: 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    NUMBER_OF_PROCESSORS: '12',
    NVM_HOME: 'D:\\application\\nvm',
    NVM_SYMLINK: 'C:\\Program Files\\nodejs',
    OneDrive: 'C:\\Users\\Zz\\OneDrive',
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    OS: 'Windows_NT',
    Path: 'D:\\application\\nvm\\v14.17.1\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;D:\\workspace\\new-share\\node_modules\\.bin;C:\\Users\\Zz\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\application\\Git\\cmd;D:\\application\\Cmder;D:\\application\\Xshell\\;D:\\flutter\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;"C:\\Program Files\\Java\\jdk1.8.0_301\\bin;C:\\Program Files\\Java\\jdk1.8.0_301\\jre\\bin;";D:\\application\\nvm;C:\\Program Files\\nodejs;D:\\application\\Cmder\\vendor\\git-for-windows\\bin;C:\\Program Files\\dotnet\\;D:\\软件文件夹\\;C:\\Users\\Zz\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C:\\Users\\Zz\\AppData\\Local\\Programs\\Python\\Python310\\;C:\\Users\\Zz\\AppData\\Local\\Microsoft\\WindowsApps;D:\\application\\Microsoft VS Code\\bin;D:\\application\\nvm;D:\\application\\nvm;C:\\Program Files\\nodejs',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.CPL',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD',
    PROCESSOR_LEVEL: '23',
    PROCESSOR_REVISION: '7100',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PROMPT: '$P$G',
    PSModulePath: 'C:\\Users\\Zz\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SESSIONNAME: 'Console',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\Zz\\AppData\\Local\\Temp',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.63.2',
    TMP: 'C:\\Users\\Zz\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-GQBECKU',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-GQBECKU',
    USERNAME: '谢小谢',
    USERPROFILE: 'C:\\Users\\Zz',
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
    VSCODE_GIT_ASKPASS_MAIN: 'd:\\application\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
    VSCODE_GIT_ASKPASS_NODE: 'D:\\application\\Microsoft VS Code\\Code.exe',
    VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-cbf20f0fc6-sock',
    windir: 'C:\\Windows'
  },
  title: 'npm',
  argv: [
    'C:\\Program Files\\nodejs\\node.exe',
    'D:\\workspace\\new-share\\node_modules\\next\\dist\\bin\\next',
    'dev'
  ],
  execArgv: [],
  pid: 1296,
  ppid: 16412,
  execPath: 'C:\\Program Files\\nodejs\\node.exe',
  debugPort: 9229,
  argv0: 'node',
  _preload_modules: [],
  mainModule: Module {
    id: '.',
    path: 'D:\\workspace\\new-share\\node_modules\\next\\dist\\bin',
    exports: {},
    parent: null,
    filename: 'D:\\workspace\\new-share\\node_modules\\next\\dist\\bin\\next',
    loaded: true,
    children: [ [Module], [Module], [Module], [Module], [Module] ],
    paths: [
      'D:\\workspace\\new-share\\node_modules\\next\\dist\\bin\\node_modules',
      'D:\\workspace\\new-share\\node_modules\\next\\dist\\node_modules',
      'D:\\workspace\\new-share\\node_modules\\next\\node_modules',
      'D:\\workspace\\new-share\\node_modules',
      'D:\\workspace\\node_modules',
      'D:\\node_modules'
    ]
  },
  __signal_exit_emitter__: EventEmitter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: Infinity,
    count: 0,
    emitted: {},
    infinite: true,
    [Symbol(kCapture)]: false
  },
  [Symbol(kCapture)]: false
}